Repository your-epk/your-epk, pull requests merged in 2021-10, with the labels that each got.

#18 Feature/set up test routing and props
  package-lock.json
  package.json
  src/components/App/App.tsx
  src/components/pages/Dashboard/Dashboard.tsx
  src/components/pages/EditPage/EditPage.tsx
  src/index.tsx
  src/types.ts
Labels: frontend, architecture, research

#25 Feature/build out dashboard
  src/components/App/App.tsx
  src/components/pages/DashboardPage/Dashboard/Dashboard.tsx
  src/components/pages/DashboardPage/EPKCard/EPKCard.tsx
  src/components/pages/DashboardPage/EPKContainer/EPKContainer.tsx
  src/components/pages/DashboardPage/TitleForm/TitleForm.tsx
  src/components/pages/EditPage/EditPage.tsx
  src/styles/main.scss
Labels: frontend, architecture, development

#36 Feature/checksum bytesize calc
  package-lock.json
  package.json
  src/awsS3/helperFunctions.js
  src/components/FilmPoster/FilmPosterForm.tsx
  src/components/pages/EditPage/EditPage.tsx
  src/utils/apiCalls.ts
Labels: architecture, development
