Repository your-epk/your-epk, pull requests merged in 2021-11, with the labels that each got.

#95 Feature/film fam setup
  package-lock.json
  src/awsS3/helperFunctions.ts
  src/components/Filmteam/FilmMemberCard.tsx
  src/components/Filmteam/FilmTeam.scss
  src/components/Filmteam/FilmTeamContainer.tsx
  src/components/Filmteam/FilmTeamDisplay.tsx
  src/components/Filmteam/FilmTeamForm.tsx
  src/components/pages/EditPage/EditPage.tsx
  src/styles/main.scss
  src/types.ts
  src/utils/apiCalls.ts
Labels: frontend, development, AWS

#98 Feature/delete award press
  src/components/App/App.tsx
  src/components/AwardsPress/AwardCard.tsx
  src/components/AwardsPress/AwardPress.scss
  src/components/AwardsPress/AwardPressDisplay.tsx
  src/components/AwardsPress/AwardPressForm.tsx
  src/components/AwardsPress/AwardsPressContainer.tsx
  src/components/AwardsPress/PressCard.tsx
  src/components/Footer/Footer.tsx
  src/components/Navigation/Navigation.tsx
  src/components/pages/DashboardPage/Dashboard/Dashboard.tsx
  src/components/pages/EditPage/EditPage.tsx
  src/components/pages/PressPage/PressPage.tsx
  src/utils/apiCalls.ts
Labels: enhancement, frontend, architecture, development

#104 Feature/error handling
  src/awsS3/helperFunctions.ts
  src/components/App/App.tsx
  src/components/AwardsPress/AwardPressDisplay.tsx
  src/components/AwardsPress/AwardsPressContainer.tsx
  src/components/AwardsPress/PressCard.tsx
  src/components/Contact/ContactForm.tsx
  src/components/Error/Error.scss
  src/components/Error/Error.tsx
  src/components/FilmDetails/FilmDetailsForm.tsx
  src/components/FilmPoster/FilmPosterForm.tsx
  src/components/Filmteam/FilmTeamContainer.tsx
  src/components/Filmteam/FilmTeamForm.tsx
  src/components/Header/HeaderContainer.tsx
  src/components/HeaderImg/HeaderImgDisplay.tsx
  src/components/HeaderImg/HeaderImgForm.tsx
  src/components/Navigation/Navigation.tsx
  src/components/Synopsis/SynopsisForm.tsx
  src/components/Taglines/TaglinesForm.tsx
  src/components/pages/DashboardPage/TitleForm/TitleForm.tsx
  src/components/pages/EditPage/EditPage.tsx
  src/components/pages/LoginPage/LoginForm.tsx
  src/components/pages/LoginPage/LoginPage.tsx
  src/components/pages/LoginPage/RegisterForm.tsx
  src/components/pages/PressPage/PressPage.tsx
  src/utils/apiCalls.ts
Labels: enhancement, frontend

#106 Feature/update UI part2
  src/components/App/App.tsx
  src/components/AwardsPress/AwardPress.scss
  src/components/AwardsPress/AwardPressForm.tsx
  src/components/FilmDetails/FilmDetails.scss
  src/components/FilmPoster/FilmPosterForm.tsx
  src/components/FilmPoster/filmPoster.scss
  src/components/FilmStills/FilmStills.scss
  src/components/FilmStills/FilmStillsCard.tsx
  src/components/FilmStills/FilmStillsForm.tsx
  src/components/Filmteam/FilmMemberCard.tsx
  src/components/Filmteam/FilmTeam.scss
  src/components/Filmteam/FilmTeamForm.tsx
  src/components/Header/Header.scss
  src/components/HeaderImg/HeaderImgForm.tsx
  src/components/Synopsis/synopsis.scss
  src/components/Taglines/Taglines.scss
  src/components/Trailer/trailer.scss
  src/components/pages/EditPage/EditPage.scss
  src/components/pages/EditPage/EditPage.tsx
  src/components/pages/LoginPage/LoginForm.tsx
  src/components/pages/LoginPage/LoginPage.scss
  src/components/pages/LoginPage/RegisterForm.tsx
  src/components/pages/PressPage/PressPage.scss
  src/components/pages/PressPage/PressPage.tsx
  src/images/logo_background.png
  src/images/logo_background2.png
  src/styles/_mixins.scss
  src/styles/main.scss
Labels: frontend, styling

#108 Fix/film crew id rename
  src/components/Filmteam/FilmTeamForm.tsx
Labels: architecture

#111 Fix/film website links
  src/components/App/App.tsx
  src/components/Contact/ContactDisplay.tsx
  src/components/Contact/ContactForm.tsx
  src/components/FilmDetails/FilmDetailsDisplay.tsx
  src/components/FilmDetails/FilmDetailsForm.tsx
  src/components/pages/EditPage/EditPage.tsx
Labels: frontend, architecture
